2023-03-15 12:44:43,060 - pyswarms.single.global_best - INFO - Optimize for 200 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-03-15 12:44:43,147 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 4.45007427233844e-11, best pos: [5.65527086e-06 3.53817103e-06]
2023-03-15 12:49:23,853 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-03-15 12:49:25,244 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 9.358904671297744e-43, best pos: [-9.04798505e-22 -3.42388861e-22]
2023-03-15 12:53:25,130 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-03-15 12:53:26,725 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2.020530040242499, best pos: [1.00862874 1.00159778]
2023-03-15 12:55:12,951 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "d:\Pliki programów\Python\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 6) and arg 1 with shape (10, 2).
2023-03-15 13:01:18,009 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "d:\Pliki programów\Python\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 6) and arg 1 with shape (10, 2).
2023-03-15 13:03:12,760 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-03-15 13:03:14,361 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.0718086287323877, best pos: [0.08974386 0.17218914 0.0379796  0.14071676 0.10188146 0.04982048]
2023-03-15 13:04:45,842 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "d:\Pliki programów\Python\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 497, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 230, in numpy.random._common.validate_output_shape
ValueError: Output size (10, 6) is not compatible with broadcast dimensions of inputs (10, 10, 6).
2023-03-15 13:05:10,997 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-03-15 13:05:12,572 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.08027163265225741, best pos: [0.16041655 0.0928021  0.00123688 0.18760579 0.10313886 0.00953135]
